-- Create issue_votes table to track individual anonymous votes
CREATE TABLE IF NOT EXISTS issue_votes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    issue_id UUID REFERENCES issues(id) ON DELETE CASCADE,
    voter_id TEXT NOT NULL, -- UUID generated by client and stored in localStorage
    vote_type TEXT NOT NULL, -- 'true' (upvote), 'false' (downvote), 'resolve'
    ip_address TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    -- Ensure a visitor can only cast one type of vote per issue
    UNIQUE(issue_id, voter_id, vote_type)
);

-- Index for performance
CREATE INDEX IF NOT EXISTS issue_votes_issue_id_idx ON issue_votes (issue_id);
CREATE INDEX IF NOT EXISTS issue_votes_voter_id_idx ON issue_votes (voter_id);
